# Generated by Django 4.2.7 on 2023-12-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='nome',
            field=models.CharField(max_length=20),
        ),
    ]
